---
- include_vars: debian.yml
  when: ansible_os_family == 'Debian'

- name: 'Check if mariadb is already installed'
  shell: mysql -V | grep -o MariaDB
  register: mariadb_installed
  ignore_errors: true
  changed_when: false

- name: Check root .my.cnf
  register: mycnf_file
  stat:
    path: '/root/.my.cnf'

- set_fact:
    mariadb_not_installed: "{{ 'true' if mariadb_installed.stdout == '' else 'false' }}"
    _mariadb_login_user: "root"
    _mariadb_login_password: ""
    _mariadb_cmd_login: ''

# If root user has been removed, use new credentials
- set_fact:
    _mariadb_login_user: "{{ mariadb_admin_user }}"
    _mariadb_login_password: "{{ mariadb_admin_password }}"
    _mariadb_cmd_login: '-u "{{ mariadb_admin_user }}" -p"{{ mariadb_admin_password }}"'
  when: mycnf_file.stat is defined and mycnf_file.stat.exists

- debug:
    var: mariadb_installed
- debug:
    var: mariadb_not_installed
- debug:
    var: mycnf_file

- include: install.yml
- include: configure.yml
- include: secure-installation.yml
- include: databases.yml
- include: users.yml
#- include: replication.yml