---
- name: User must exist on master
  mariadb_user:
    name: "{{ mariadb_replication_user.name }}"
    host: "{{ mariadb_replication_user.host | default('%') }}"
    password: "{{ mariadb_replication_user.password }}"
    priv: "{{ mariadb_replication_user.priv | default('*.*:REPLICATION SLAVE') }}"
    state: present
  when: >
    (mariadb_replication_role == 'master')
    and mariadb_replication_user
    and (mariadb_replication_master != '')
    
- name: Check replication status (slave)
  mariadb_replication:
    mode: getslave
  ignore_errors: true
  register: slave
  when: >
    mariadb_replication_role == 'slave'
    and (mariadb_replication_master != '')

- name: Check replication status (master)
  mariadb_replication:
    mode: getmaster
  delegate_to: "{{ mariadb_replication_master }}"
  register: master
  when: >
    slave|failed
    and (mariadb_replication_role == 'slave')
    and (mariadb_replication_master != '')

- name: Configure slave
  mariadb_replication:
    mode: changemaster
    master_host: "{{ mariadb_replication_master }}"
    master_user: "{{ mariadb_replication_user.name }}"
    master_password: "{{ mariadb_replication_user.password }}"
    master_log_file: "{{ master.File }}"
    master_log_pos: "{{ master.Position }}"
  ignore_errors: true
  when: >
    slave|failed
    and (mariadb_replication_role == 'slave')
    and (mariadb_replication_master != '')
    and mariadb_replication_user

- name: Start replication
  mariadb_replication: mode=startslave
  when: >
    slave|failed
    and (mariadb_replication_role == 'slave')
    and (mariadb_replication_master != '')