---
- name: Manage mariadb users
  mysql_user:
    name: "{{ item.name }}"
    host: "{{ item.host | default('localhost') }}"
    password: "{{ item.password }}"
    priv: "{{ item.priv | default('*.*:USAGE') }}"
    state: present
    append_privs: "{{ item.append_privs | default('no') }}"
    login_user: '{{ _mariadb_login_user }}'
    login_password: '{{ _mariadb_login_password }}'
  with_items: mariadb_users

# For all localhost users create 127.0.0.1 alias
- name: Manage mariadb users
  mysql_user:
    name: "{{ item.name }}"
    host: "127.0.0.1"
    password: "{{ item.password }}"
    priv: "{{ item.priv | default('*.*:USAGE') }}"
    state: present
    append_privs: "{{ item.append_privs | default('no') }}"
    login_user: '{{ _mariadb_login_user }}'
    login_password: '{{ _mariadb_login_password }}'
  when: (item.host is not defined or item.host == 'localhost') and mariadb_users_create_ip_alias
  with_items: mariadb_users